"""Interactive dashboard for HIV‑1 protease ML pipeline.

Uses Streamlit to let the user explore classification and regression results, feature importance,
and applicability‑domain statistics.
"""

import streamlit as st
import pandas as pd
import numpy as np
from pathlib import Path

# Import the interactive plot functions from the main script
from drug_interaction_ml import (
    plot_roc_curves_interactive,
    plot_precision_recall_curves_interactive,
    plot_feature_importance_interactive,
    plot_regression_predictions,
)

# Paths to artefacts generated by the pipeline (relative to repo root)
DATA_DIR = Path('.')
CLASS_METRICS = DATA_DIR / "classification_metrics_v3.csv"
REGRESSION_METRICS = DATA_DIR / "regression_metrics_v3.csv"
CLASS_PRED = DATA_DIR / "classification_predictions_v3.csv"
REG_PRED = DATA_DIR / "regression_predictions_v3.csv"
FEATURE_IMPORTANCE_PATH = DATA_DIR / "feature_importance.png"  # fallback static image

st.title("HIV‑1 Protease ML Pipeline Dashboard")

# Load classification metrics
if CLASS_METRICS.exists():
    class_df = pd.read_csv(CLASS_METRICS)
    st.subheader("Classification Summary")
    st.dataframe(class_df)
else:
    st.warning("Classification metrics file not found.")

# Load regression metrics
if REGRESSION_METRICS.exists():
    reg_df = pd.read_csv(REGRESSION_METRICS)
    st.subheader("Regression Summary")
    st.dataframe(reg_df)
else:
    st.warning("Regression metrics file not found.")

# ------------------------------------------------------------------
# Interactive plots
# ------------------------------------------------------------------
if CLASS_PRED.exists():
    pred_df = pd.read_csv(CLASS_PRED)
    y_true = pred_df["label"].to_numpy()
    y_prob = pred_df[[col for col in pred_df.columns if col.startswith("prob_")]].to_numpy()
    # Build dummy ClassificationResult objects for Plotly functions
    class ClassificationResult:
        def __init__(self, name, y_prob, roc_auc, pr_auc):
            self.name = name
            self.y_prob = y_prob
            self.roc_auc = roc_auc
            self.pr_auc = pr_auc
    results = []
    for col in pred_df.columns:
        if col.startswith("prob_"):
            model_name = col.replace("prob_", "")
            probs = pred_df[col].to_numpy()
            # Compute AUCs on the fly for quick display
            from sklearn.metrics import roc_auc_score, average_precision_score
            roc_auc = float(roc_auc_score(y_true, probs))
            pr_auc = float(average_precision_score(y_true, probs))
            results.append(ClassificationResult(model_name, probs, roc_auc, pr_auc))
    st.subheader("ROC Curves (interactive)")
    fig_roc = plot_roc_curves_interactive(results, y_true)
    st.plotly_chart(fig_roc)

    st.subheader("Precision‑Recall Curves (interactive)")
    fig_pr = plot_precision_recall_curves_interactive(results, y_true)
    st.plotly_chart(fig_pr)
else:
    st.warning("Classification predictions file not found – cannot render interactive curves.")

# Regression predictions plot (static Matplotlib saved image)
if REG_PRED.exists():
    st.subheader("Regression Predictions (static plot)")
    # Load and display the saved PNG image
    from PIL import Image
    img = Image.open(str(DATA_DIR / "regression_predictions.png"))
    st.image(img, caption="Regression Predictions", use_column_width=True)
else:
    st.warning("Regression predictions image not found.")

# Feature importance – attempt to load the model for interactive plot
st.subheader("Feature Importance")
if FEATURE_IMPORTANCE_PATH.exists():
    # Load the static PNG as fallback
    from PIL import Image
    img = Image.open(str(FEATURE_IMPORTANCE_PATH))
    st.image(img, caption="Feature Importance (static)", use_column_width=True)
else:
    st.info("Feature importance image not available.")

st.caption("Dashboard powered by Streamlit and Plotly. Generated from the pipeline artefacts in the repository.")
